[build]
  builder = "NIXPACKS"
  watchPatterns = ["star_backend_flask/**"]

[[services]]
  internalHostname = "star-backend"
  instanceCount = 1
  instanceSizeSlug = "CPU_0.5"

  [services.source]
    git = "github.com/RunDumy/Star"
    dir = "star-backend/star_backend_flask"
    rootDir = "star-backend"

  [services.assignments]
    [[services.assignments.deploy]]
      deploymentStrategy = "BLUE_GREEN"
    [[services.assignments.deploy]]
      service = "star-backend"

  [services.http]
    port = 5000
    gracePeriod = 300

  [services.healthcheck]
    path = "/api/health"
    timeout = 300

  [[services.ports]]
    port = 5000
    forceHttps = true

  [[services.env]]
    PYTHON_VERSION = "3.13.4"
    PORT = "5000"
    SUPABASE_URL = "https://hiwmpmvqcxzshdmhhlsb.supabase.co"
    SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpd21wbXZxY3h6c2hkbWhoZHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MzY4NTUsImV4cCI6MjA0ODMxMjg1NX0.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
    SECRET_KEY = "ab81305c0f2092fe2d0d0467e24fb3533ea04ea10bcb2aed51c59b7abe920ac7"
    JWT_SECRET_KEY = "da779a84173a2ec911e5b5149bab652fb0c951ba904ad11837fafbb666bdc0f2"
    JWT_ALGORITHM = "HS256"
    AGORA_APP_ID = "d146ac692e604e7b9a99c9568ccbcd23"
    AGORA_APP_CERTIFICATE = "f5e4c9a8466141d588644f9043ce4a84"
    REDIS_HOST = "redis-11341.c246.us-east-1-4.ec2.redns.redis-cloud.com"
    REDIS_PORT = "11341"
    REDIS_USERNAME = "default"
    REDIS_PASSWORD = "dpQqYc6wimd8CoOazLDvrE6TlNt4un6b"
    SPOTIPY_CLIENT_ID = "dcc37439570a47b1a79db76e3bd35a22"
    SPOTIPY_CLIENT_SECRET = "c2e06d864bca407bab4a6dfbf80993d5"
    ALLOWED_ORIGINS = "https://star-frontend.vercel.app"

  [services.start]
    command = "gunicorn --threads 4 -b 0.0.0.0:$PORT --chdir star_backend_flask app:app"