[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "gunicorn --threads 4 -b 0.0.0.0:$PORT app:app"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[[services]]
  id = "star-backend"
  name = "star-backend"
  source = { repo = "github.com/RunDumy/Star", path = "star-backend/star_backend_flask" }
  instanceCount = 1
  instanceSizeSlug = "CPU_0.5"

  [services.http]
    port = 5000
    forceHttps = true

  [[services.env]]
    key = "PYTHON_VERSION"
    value = "3.13.4"

  [[services.env]]
    key = "PORT"
    value = "5000"

  [[services.env]]
    key = "AGORA_APP_ID"
    value = "d146ac692e604e7b9a99c9568ccbcd23"

  [[services.env]]
    key = "AGORA_APP_CERTIFICATE"
    value = "f5e4c9a8466141d588644f9043ce4a84"

  [[services.env]]
    key = "REDIS_URL"
    value = "${{shared.REDIS_URL}}"

  [[services.env]]
    key = "SUPABASE_URL"
    value = "${{shared.SUPABASE_URL}}"

  [[services.env]]
    key = "SUPABASE_ANON_KEY"
    value = "${{shared.SUPABASE_ANON_KEY}}"

  [[services.env]]
    key = "SECRET_KEY"
    value = "8d6448401426f23350520f5b4d4dadb088a9e6be0fb2ecc86a206b7cb358b722"

  [[services.env]]
    key = "JWT_SECRET"
    value = "55bd7933fcfd0f10912b92788a36e0124a2e7c2330b586bfae32d2d28e9da16e"

  [[services.env]]
    key = "JWT_ALGORITHM"
    value = "HS256"

  [[services.env]]
    key = "ALLOWED_ORIGINS"
    value = "https://star-frontend.vercel.app,http://localhost:3000"

  [[services.env]]
    key = "SPOTIPY_CLIENT_ID"
    value = "${{shared.SPOTIPY_CLIENT_ID}}"

  [[services.env]]
    key = "SPOTIPY_CLIENT_SECRET"
    value = "${{shared.SPOTIPY_CLIENT_SECRET}}"