services:
  - type: web
    name: star-backend-web
    runtime: python
    region: oregon
    plan: free
    rootDir: star-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn star_backend_flask.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: SPOTIFY_CLIENT_ID
        value: <REDACTED_SPOTIFY_CLIENT_ID>
      - key: SPOTIFY_CLIENT_SECRET
        generateValue: true
      - key: IPGEOLOCATION_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://your-vercel-app.vercel.app
      - key: PORT
        value: 5000
      - key: FLASK_DEBUG
        value: 0
      - key: SUPABASE_URL
        value: <REDACTED_SUPABASE_URL>
      - key: SUPABASE_ANON_KEY
        generateValue: true
      - key: DATABASE_URL
        generateValue: true
