version: "3.8"

# Development overrides for docker-compose.yml
# This file is automatically merged with docker-compose.yml when running docker-compose

services:
  # Development backend with hot reload
  flask:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ../../star-backend:/app
    command: ["python", "star_backend_flask/app.py"]

  # Development frontend with hot reload
  frontend:
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

  # Development tools can be added here if needed
