# star-backend/docker-compose.yml
version: "3.8"

services:
  flask:
    build:
      context: ../../star-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
      - PORT=5000
      - AGORA_APP_ID=${AGORA_APP_ID}
      - AGORA_APP_CERTIFICATE=${AGORA_APP_CERTIFICATE}
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - star-network

  frontend:
    build:
      context: ../../star-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - flask
    volumes:
      - ../../star-frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - star-network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - star-network

  supabase:
    image: supabase/postgres:15.1.0.147
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_password_change_me}
      - POSTGRES_DB=postgres
    volumes:
      - supabase-data:/var/lib/postgresql/data
    networks:
      - star-network

volumes:
  redis-data:
  supabase-data:

networks:
  star-network:
    driver: bridge
