[build]
  builder = "NIXPACKS"

[[services]]
  internalPort = 5000
  autoStart = true
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    timeout = 2000