[build]
  builder = "NIXPACKS"
  watchPatterns = ["star_backend_flask/**"]

[[services]]
  internalHostname = "star-backend"
  instanceCount = 1
  instanceSizeSlug = "CPU_0.5"

  [services.source]
    git = "github.com/RunDumy/Star"
    dir = "star-backend/star_backend_flask"
    rootDir = "star-backend"

  [services.assignments]
    [[services.assignments.deploy]]
      deploymentStrategy = "BLUE_GREEN"
    [[services.assignments.deploy]]
      service = "star-backend"

  [services.http]
    port = 5000
    gracePeriod = 300

  [[services.ports]]
    port = 5000
    forceHttps = true

  [[services.env]]
    PYTHON_VERSION = "3.13.4"
    PORT = "5000"
    SUPABASE_URL = "${{shared.SUPABASE_URL}}"
    SUPABASE_ANON_KEY = "${{shared.SUPABASE_ANON_KEY}}"
    SECRET_KEY = "${{shared.SECRET_KEY}}"
    JWT_SECRET = "${{shared.JWT_SECRET}}"
    JWT_ALGORITHM = "HS256"
    REDIS_URL = "${{shared.REDIS_URL}}"
    AGORA_APP_ID = "${{shared.AGORA_APP_ID}}"
    AGORA_APP_CERTIFICATE = "${{shared.AGORA_APP_CERTIFICATE}}"
    SPOTIPY_CLIENT_ID = "${{shared.SPOTIPY_CLIENT_ID}}"
    SPOTIPY_CLIENT_SECRET = "${{shared.SPOTIPY_CLIENT_SECRET}}"
    ALLOWED_ORIGINS = "https://star-frontend.vercel.app"
