services:
  - type: web
    name: Star
    runtime: python
    repo: https://github.com/RunDumy/Star
    plan: free
    region: virginia
    buildCommand: cd star-backend && pip install -r requirements.txt
    startCommand: cd star-backend/star_backend_flask && gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeployTrigger: "off"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: IPGEOLOCATION_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
