services:
  - type: web
    name: star-backend
    runtime: python
    rootDir: star-backend/star_backend_flask
    repo: https://github.com/RunDumy/Star
    plan: free
    region: virginia
    buildCommand: pip install -r ../requirements.txt -c ../constraints.txt
    preDeployCommand: python init_db.py
    startCommand: exec gunicorn --chdir star-backend/star_backend_flask -b 0.0.0.0:$PORT app:app
    autoDeployTrigger: "commit"
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: IPGEOLOCATION_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_APP_CERTIFICATE
        sync: false
      - key: REDIS_URL
        sync: false
