services:
  - type: web
    name: star-backend
    runtime: python
    repo: https://github.com/RunDumy/Star
    plan: free
    region: virginia
    buildCommand: cd star-backend && pip install -r requirements.txt -c constraints.txt
    preDeployCommand: cd star-backend/star_backend_flask && python init_db.py
    startCommand: cd star-backend/star_backend_flask && gunicorn --chdir star_backend_flask app:app --bind 0.0.0.0:$PORT
    autoDeployTrigger: "commit"
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: IPGEOLOCATION_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_APP_CERTIFICATE
        sync: false
      - key: REDIS_URL
        sync: false
