# railway.toml - Updated configuration for Star Backend Flask
[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[[services]]
  internalHostname = "star-backend"
  instanceCount = 1
  instanceSizeSlug = "CPU_0.5"

  [services.source]
    git = "github.com/RunDumy/Star"
    dir = "star-backend/star_backend_flask"
    rootDir = "star-backend"

  [services.assignments]
    [[services.assignments.deploy]]
      deploymentStrategy = "BLUE_GREEN"
    [[services.assignments.deploy]]
      service = "star-backend"

  [services.http]
    port = 5000
    gracePeriod = 300

  [[services.ports]]
    port = 5000
    forceHttps = true

  [[services.env]]
    PYTHON_VERSION = "3.13.4"
    PORT = "5000"
    SUPABASE_URL = "https://hiwmpmvqcxzshdmhhlsb.supabase.co"
    SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpd21wbXZxY3h6c2hkbWhobHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDAzMjcsImV4cCI6MjA3NDUxNjMyN30.RXa8Bx3Pwy9Du2j-XD8WaGDjuCVe9H-PLTgMLJa11ZE"
    SECRET_KEY = "8d6448401426f23350520f5b4d4dadb088a9e6be0fb2ecc86a206b7cb358b722"
    JWT_SECRET = "55bd7933fcfd0f10912b92788a36e0124a2e7c2330b586bfae32d2d28e9da16e"
    JWT_ALGORITHM = "HS256"
    REDIS_URL = "redis://default:dpQqYc6wimd8CoOazLDvrE6TlNt4un6b@redis-11341.c246.us-east-1-4.ec2.redns.redis-cloud.com:11341"
    REDIS_HOST = "redis-11341.c246.us-east-1-4.ec2.redns.redis-cloud.com"
    REDIS_PORT = "11341"
    REDIS_USERNAME = "default"
    REDIS_PASSWORD = "dpQqYc6wimd8CoOazLDvrE6TlNt4un6b"
    AGORA_APP_ID = "d146ac692e604e7b9a99c9568ccbcd23"
    AGORA_APP_CERTIFICATE = "f5e4c9a8466141d588644f9043ce4a84"
    SPOTIPY_CLIENT_ID = "dcc37439570a47b1a79db76e3bd35a22"
    SPOTIPY_CLIENT_SECRET = "c2e06d864bca407bab4a6dfbf80993d5"
    ALLOWED_ORIGINS = "https://star-frontend.vercel.app"

  [services.start]
    command = "./railway_start.sh"
