# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: star-platform
metadata:
    template: azd-init@1.20.0
services:
    backend:
        project: ./star-backend/star_backend_flask
        language: python
        host: containerapp
        docker:
            path: ./Dockerfile
    frontend:
        project: ./star-frontend
        language: js
        host: staticwebapp
        dist: .next
