$connectionString = $env:AZURE_STORAGE_CONNECTION_STRING
$containerName = "assets"

# List of specific asset files to upload
$assetFiles = @(
    "C:\Users\fudos\Downloads\Icons8\icons8-libra-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-pisces-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-pisces-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-sagittarius-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-sagittarius-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-scorpio-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-scorpio-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-taurus-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-taurus-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-virgo-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-virgo-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-aquarius-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-aquarius-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-aries-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-aries-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-cancer-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-cancer-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-capricorn-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-capricorn-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-gemini-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-gemini-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-leo-50.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-leo-100.png",
    "C:\Users\fudos\Downloads\Icons8\icons8-libra-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-rabbit-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-rat-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-rat-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-rooster-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-rooster-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-snake-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-snake-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-tiger-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-tiger-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-dog-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-dog-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-dragon-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-dragon-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-goat-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-goat-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-horse-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-horse-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-monkey-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-monkey-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-ox-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-ox-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-pig-50.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-pig-100.png",
    "C:\Users\fudos\Downloads\Icons8 (1)\icons8-year-of-rabbit-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-moon-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-neptune-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-neptune-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-pluto-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-pluto-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-saturn-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-saturn-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-sun-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-sun-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-uranus-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-uranus-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-venus-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-venus-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-water-element-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-water-element-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-air-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-air-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-earth-element-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-earth-element-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-earth-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-earth-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-fire-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-fire-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-jupiter-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-jupiter-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-mars-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-mars-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-mercury-50.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-mercury-100.png",
    "C:\Users\fudos\Downloads\Icons8 (2)\icons8-moon-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-earth-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-earth-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-fire-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-fire-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-first-quarter-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-first-quarter-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-full-moon-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-full-moon-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-gemini-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-gemini-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-jupiter-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-jupiter-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-last-quarter-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-last-quarter-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-leo-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-leo-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-libra-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-libra-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-mars-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-mars-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-mercury-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-mercury-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-moon-and-stars-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-moon-and-stars-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-moon-phase-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-moon-phase-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-moon-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-moon-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-neptune-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-neptune-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-new-moon-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-new-moon-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-pisces-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-pisces-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-pluto-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-pluto-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-sagittarius-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-sagittarius-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-saturn-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-saturn-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-scorpio-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-scorpio-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-spring-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-spring-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-summer-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-summer-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-sun-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-sun-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-taurus-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-taurus-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-uranus-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-uranus-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-venus-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-venus-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-virgo-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-virgo-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-waning-crescent-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-waning-crescent-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-waning-gibbous-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-waning-gibbous-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-water-element-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-water-element-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-waxing-crescent-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-waxing-crescent-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-waxing-gibbous-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-waxing-gibbous-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-winter-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-winter-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-dog-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-dog-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-dragon-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-dragon-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-goat-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-goat-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-horse-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-horse-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-monkey-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-monkey-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-ox-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-ox-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-pig-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-pig-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-rabbit-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-rabbit-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-rat-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-rat-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-rooster-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-rooster-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-snake-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-snake-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-tiger-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-year-of-tiger-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-air-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-air-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-aquarius-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-aquarius-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-aries-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-aries-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-autumn-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-autumn-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-cancer-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-cancer-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-capricorn-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-capricorn-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-crescent-moon-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-crescent-moon-100.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-earth-element-50.png",
    "C:\Users\fudos\Downloads\Icons8 (5)\icons8-earth-element-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-pig-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-rabbit-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-rabbit-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-rat-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-rooster-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-rooster-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-snake-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-snake-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-tiger-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-tiger-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-mars-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-sun-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-rat-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-air-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-air-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-autumn-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-autumn-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-earth-element-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-earth-element-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-earth-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-earth-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-fire-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-fire-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-jupiter-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-jupiter-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-mars-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-mercury-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-mercury-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-moon-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-moon-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-neptune-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-neptune-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-pluto-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-pluto-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-saturn-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-saturn-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-spring-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-spring-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-summer-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-summer-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-sun-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-uranus-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-uranus-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-venus-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-venus-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-water-element-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-water-element-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-winter-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-winter-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-dog-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-dog-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-dragon-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-dragon-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-goat-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-goat-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-horse-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-horse-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-monkey-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-monkey-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-ox-50.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-ox-100.png",
    "C:\Users\fudos\Downloads\Icons8 (4)\icons8-year-of-pig-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-monkey-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-ox-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-ox-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-pig-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-pig-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-rabbit-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-rabbit-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-rat-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-rat-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-rooster-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-rooster-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-snake-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-snake-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-tiger-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-tiger-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-air-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-air-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-autumn-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-autumn-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-earth-element-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-earth-element-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-earth-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-earth-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-fire-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-fire-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-jupiter-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-jupiter-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-mars-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-mars-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-mercury-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-mercury-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-moon-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-moon-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-neptune-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-neptune-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-pluto-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-pluto-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-saturn-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-saturn-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-spring-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-spring-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-summer-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-summer-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-sun-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-sun-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-uranus-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-uranus-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-venus-symbol-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-venus-symbol-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-water-element-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-water-element-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-winter-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-winter-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-dog-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-dog-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-dragon-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-dragon-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-goat-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-goat-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-horse-50.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-horse-100.png",
    "C:\Users\fudos\Downloads\Icons8 (7)\icons8-year-of-monkey-50.png",
    "C:\Users\fudos\Downloads\whoosh-truck-2-386138.mp3",
    "C:\Users\fudos\Downloads\whoosh-bamboo-389752.mp3",
    "C:\Users\fudos\Downloads\whoosh-velocity-383019.mp3",
    "C:\Users\fudos\Downloads\whoosh-sound-effect-240257.mp3",
    "C:\Users\fudos\Downloads\whoosh-dark-tension-386134.mp3",
    "C:\Users\fudos\Downloads\whoosh-flame-388763.mp3",
    "C:\Users\fudos\Downloads\whoosh-motion-3-390710.mp3",
    "C:\Users\fudos\Downloads\whoosh-door-388765.mp3",
    "C:\Users\fudos\Downloads\whoosh-torch-2-388764.mp3",
    "C:\Users\fudos\Downloads\whoosh-axe-throw-389751.mp3",
    "C:\Users\fudos\Downloads\blank tarot.PNG"
)

Write-Host "Starting upload of $($assetFiles.Count) asset files to Azure Blob Storage..."

foreach ($filePath in $assetFiles) {
    if (Test-Path $filePath) {
        $fileName = [System.IO.Path]::GetFileName($filePath)
        Write-Host "Uploading $fileName..."
        try {
            az storage blob upload --connection-string $connectionString --container-name $containerName --name $fileName --file $filePath --metadata "encrypted=true"
            Write-Host "Successfully uploaded $fileName"
        } catch {
            Write-Host "Failed to upload $fileName : $_"
        }
    } else {
        Write-Host "File not found: $filePath"
    }
}

Write-Host "Upload process completed!"