name: Deploy STAR to Azure App Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Set up permissions for deploying with secretless Azure federated credentials
permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
  AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          cd star-backend
          pip install -r star_backend_flask/requirements.txt

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies and build
        run: |
          cd star-frontend
          npm ci
          npm run build

      - name: Copy frontend build to backend
        run: |
          mkdir -p star-backend/star_backend_flask/static
          cp -r star-frontend/out/* star-backend/star_backend_flask/static/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Build frontend
        run: |
          cd star-frontend
          npm ci
          npm run build

      - name: Copy frontend build to backend
        run: |
          mkdir -p star-backend/star_backend_flask/static
          cp -r star-frontend/out/* star-backend/star_backend_flask/static/

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"

      - name: Provision Infrastructure
        run: azd provision --no-prompt

      - name: Deploy Application
        run: azd deploy --no-prompt
