name: STAR Monorepo CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    frontend:
        uses: ./.github/workflows/frontend.yml

    backend:
        uses: ./.github/workflows/backend.yml

    success:
        needs: [frontend, backend]
        if: always()
        runs-on: ubuntu-latest
        steps:
            - name: Check All Jobs Passed
              run: |
                  if [[ "${{ needs.frontend.result }}" == "success" && "${{ needs.backend.result }}" == "success" ]]; then
                    echo "All jobs passed!"
                  else
                    echo "Some jobs failed!"
                    exit 1
                  fi
