name: Deploy STAR Platform to Azure
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    AZURE_WEBAPP_NAME: star-backend-app
    AZURE_WEBAPP_PACKAGE_PATH: "./star-backend/star_backend_flask"
    NODE_VERSION: "18"
    PYTHON_VERSION: "3.9"

jobs:
    build-and-deploy-backend:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            - name: Create virtual environment
              run: python -m venv venv

            - name: Activate virtual environment
              run: source venv/bin/activate

            - name: Install dependencies
              run: |
                  source venv/bin/activate
                  cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
                  pip install -r requirements.txt

            - name: Collect static files (if needed)
              run: |
                  source venv/bin/activate
                  cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
                  # Add any static file collection if needed

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    build-and-deploy-frontend:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: "./star-frontend/package-lock.json"

            - name: Install dependencies
              run: |
                  cd ./star-frontend
                  npm ci

            - name: Build application
              run: |
                  cd ./star-frontend
                  npm run build

            - name: Deploy to Azure Static Web Apps
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: "upload"
                  app_location: "./star-frontend"
                  api_location: ""
                  output_location: "out"

    test-deployment:
        runs-on: ubuntu-latest
        needs: [build-and-deploy-backend, build-and-deploy-frontend]

        steps:
            - name: Test backend health endpoint
              run: |
                  sleep 30  # Wait for deployment to settle
                  curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health || exit 1

            - name: Test zodiac arena endpoints
              run: |
                  curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/v1/zodiac-arena/leaderboard || exit 1
